engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
- db/migrate/**/*
- config/**/*
- app/assets/javascripts/admin/jquery-ui.js
- app/assets/javascripts/admin/modernizr.js
- app/assets/bower_components/**/*
- app/assets/javascripts/ckeditor/*
- app/assets/javascripts/lib/rad_social/jquery.validate.min.js
