version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      config: .eslintrc.js
  fixme:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  haml-lint:
    enabled: true
  reek:
    enabled: true
    checks:
      IrresponsibleModule:
        enabled: false
      UncommunicativeName:
        enabled: false
      UncommunicativeVariableName:
        enabled: false
  rubocop:
    enabled: true
    channel: rubocop-1-21-0
  stylelint:
    enabled: true
exclude_patterns:
  - .rubocop.yml
  - spec/**/*
  - "**/vendor/**/*"
  - db/migrate/**/*
  - db/schema.rb
  - config/**/*
  - app/assets/javascripts/admin/jquery.validate.min.js
  - app/assets/javascripts/admin/persist.min.js
  - app/assets/javascripts/rad_social/jquery.validate.min.js
  - app/assets/javascripts/admin/modernizr.js
  - app/assets/javascripts/ckeditor/*
  - lib/configuration_extensions/configuration_extensions.rb
