version: "2"
checks:
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      config: .eslintrc.js
  fixme:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  haml-lint:
    enabled: true
    checks:
      HamlLint/FinalNewline:
        enabled: false
      HamlLint/RuboCop:
        enabled: false
  reek:
    enabled: true
    checks:
      IrresponsibleModule:
        enabled: false
      UncommunicativeName:
        enabled: false
      UncommunicativeVariableName:
        enabled: false
  rubocop:
    enabled: true
    channel: rubocop-1-56-3
  stylelint:
    enabled: true
exclude_patterns:
  - .rubocop.yml
  - spec/**/*
  - "**/vendor/**/*"
  - db/migrate/**/*
  - db/schema.rb
  - config/**/*
  - app/assets/javascripts/admin/jquery.validate.min.js
  - app/assets/javascripts/admin/persist.min.js
  - app/assets/javascripts/admin/modernizr.js
  - app/assets/javascripts/ckeditor/*
  - lib/configuration_extensions/configuration_extensions.rb
  - lib/generators/extension_model/templates/*
  - lib/generators/extension/templates/*
  - lib/generators/extension_controller/templates/*
  - lib/generators/extension_mailer/templates/*
  - lib/generators/extension_migration/templates/*
  - lib/generators/instance/templates/instance_environment.rb
  - lib/generators/language_extension/templates/
  - lib/tasks/convoy_seed_util.rb