#
# This is only an example configuration. Please see the Rails
# documentation for more details.
#

development:
  adapter: mysql2
  database: trusty_cms_dev
  username: root
  password:
  host: localhost

test: &TEST
  adapter: mysql2
  database: trusty_cms_test
  username: root
  password: ''
  host: '127.0.0.1'
  port: 3306
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin

production:
  adapter: mysql2
  database: trusty_cms_live
  username: root
  password:
  socket: /tmp/mysql.sock

cucumber:
  <<: *TEST
