version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node
      - image: circleci/mysql:5.7
        environment:
          - RAILS_ENV: test
          - MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    executor: ruby/default
    working_directory: ~/trusty-cms
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Bundler
          command: gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
      - run:
          name: Bundle Install
          command: bundle install --jobs=5 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache
      - run:
          name: install JavaScript dependencies
          command: yarn install --modules-folder spec/dummy/node_modules
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: DB Setup
          command: bundle exec rake app:db:create && bundle exec rake app:db:migrate
      - run:
          name: "Update Node.js and npm"
          command: |
            curl -sSL "https://nodejs.org/dist/v14.13.1/node-v14.13.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v14.13.1-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run: mkdir /tmp/test-results
      - run:
          command: bundle exec rspec --format progress -o /tmp/test-results/rspec.xml --profile 10 $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
          when: always
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
