#
# This is only an example configuration. Please see the Rails
# documentation for more details.
#
defaults: &defaults
  adapter:  mysql
  db:     localhost

development:
  adapter: mysql2
  database: trusty_cms_dev
  username: root
  password:

test: &TEST
  adapter:  mysql2
  database: trusty_cms_test
  username: root
  password: ''
  db: '127.0.0.1'
  port: 0
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin

production:
  adapter: mysql2
  database: trusty_cms_live
  username: root
  password:
